### ISSUE TITLE
Question rather than issue?

### ISSUE THREAD

**Issue by koepae** [MarginallyClever/Daisy-Driver-2.0-firmware#1]
Hi Dan! 

Which arduino core/ide is used for the daisy driver?

Is the stm32f103 version still available somewhere?

Rgds,
Tapio

**Comment by i-make-robots** [comment]
STM32F407.  I don't know where F103 is still available.

**Comment by i-make-robots** [comment]
STM32F407.  I don't know where F103 is still available.
